#!/usr/bin/env bash

export PATH="$PATH:$HOME/vendor/mono/bin"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/vendor/mono/lib"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$HOME/vendor/mono/lib/pkgconfig"

#export MONO_IOMAP=all
#export MONO_THREADS_PER_CPU=2048
#export MONO_GC_PARAMS=major=marksweep-par-fixed,max-heap-size=$MEMORY_LIMIT

echo "* Start application on port ${PORT}..."
mono --gc=sgen *.exe ${PORT}
